DO $$
BEGIN
  CREATE TYPE "Status" AS ENUM ('NEVER_SIGNED_IN','NO_PURCHASE','NOT_ACTIVE','ACTIVE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "status" "Status" DEFAULT 'NEVER_SIGNED_IN';